// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlqCRpWXiEUbUE59wGMvArhAcIR-2BOP4',
    appId: '1:628211897163:web:ab70ef197b99ab00cb8ece',
    messagingSenderId: '628211897163',
    projectId: 'sushior-a85a2',
    authDomain: 'sushior-a85a2.firebaseapp.com',
    storageBucket: 'sushior-a85a2.firebasestorage.app',
    measurementId: 'G-5YNSWJSS3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAX7FFP2Pe5daAWxlKTArhc44MLsRk9HQ',
    appId: '1:628211897163:android:bcb9c90a3303c4a8cb8ece',
    messagingSenderId: '628211897163',
    projectId: 'sushior-a85a2',
    storageBucket: 'sushior-a85a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEmgyJmsxRWxExNGlkbYmd7M5SrOkMxeI',
    appId: '1:628211897163:ios:00c72aba8d0f13accb8ece',
    messagingSenderId: '628211897163',
    projectId: 'sushior-a85a2',
    storageBucket: 'sushior-a85a2.firebasestorage.app',
    iosBundleId: 'com.example.sushior',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEmgyJmsxRWxExNGlkbYmd7M5SrOkMxeI',
    appId: '1:628211897163:ios:00c72aba8d0f13accb8ece',
    messagingSenderId: '628211897163',
    projectId: 'sushior-a85a2',
    storageBucket: 'sushior-a85a2.firebasestorage.app',
    iosBundleId: 'com.example.sushior',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlqCRpWXiEUbUE59wGMvArhAcIR-2BOP4',
    appId: '1:628211897163:web:2376bd69efde90fecb8ece',
    messagingSenderId: '628211897163',
    projectId: 'sushior-a85a2',
    authDomain: 'sushior-a85a2.firebaseapp.com',
    storageBucket: 'sushior-a85a2.firebasestorage.app',
    measurementId: 'G-PJ1NK2TMSF',
  );
}
